export const validPaths = [
    "/", 
    "/dashboard/employee", 
    "/dashboard/reviewer", 
    "/dashboard/admin",
    "/reimbursement/bbm", 
    "/reimbursement/operasional",
    "/reimbursement/umum", 
    "/reimbursement/detail", 
    "/reimbursement/cek-pengajuan",
    "/lpj/umum", 
    "/lpj/marketing",
    "/lpj/detail",
    "/lpj/cek-pengajuan",
    "/manage-users",
    "/manage-users/add",
    "/manage-users/edit",
    "/create-bs/create",
    "/create-bs/cek-pengajuan",

];
